# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
url: https://smdsbz.github.io
baseurl: /
title: "Xiaoguang Zhu's Blog"
description: >
    CS Undergrad @ HUST


## => Language and Timezone
##############################
lang: en
timezone: Asia/Shanghai


## => Author and Social
##############################
author:
  name: Xiaoguang Zhu
  avatar: ./assets/images/swag-dog.jpg
  email: steamstuffedbun@gmail.com
  # twitter: TODO
  github: smdsbz
  # googleplus: TODO
  # weibo: TODO
  # douban: TODO


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: smdsbz/smdsbz.github.io
repository_tree: master


## => Paths
##############################
paths:
  root: /blog
  home: /blog
  archive: /blog/archive.html
  rss:  /feed.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## license
license: CC-BY-NC-4.0


## => Themes
##############################
text_skin: forest
highlight_theme: tomorrow


## => Paginate
##############################
paginate: 7
paginate_path: /blog/page:num


## => Comments
##############################
comments:
  provider: gitalk
  gitalk:
    clientID    : 3793f3613e5597e98621
    clientSecret: 627cc23140d8aff1474645feddbd46a68dc41007
    repository  : smdsbz/smdsbz.github.io
    owner       : smdsbz
    admin:
      - smdsbz


## => Pageview
##############################
pageview:
  provider: leancloud
  leancloud:
    app_id: 1AW2cAb1zQmW1iCS5EXu26Pf-gzGzoHsz
    app_key: aQ0HJDT7L5nQlFmqGXKjJVHw
    app_class: github-page


## => Analytics
##############################
# analytics:
#   provider: google
#   google:
#     tracking_id: UA-71907556-1

toc:
  selectors: "h1,h2,h3"

## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true
      mathjax: true
      mermaid: true
      chart: true


## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji


sources: bootcdn

## => Server
##############################
server_url: "0.0.0.0"
port: 4001